### ISSUE TITLE
Log in / register panel creation and testing

### ISSUE THREAD

**Issue by Erikas-Ramanauskas** [JoyZadan/emergency-code#29]
In the testing folder, I added a section for logging in and registering buttons. please implement functionally, test, and update the testing file.

**Comment by Erikas-Ramanauskas** [comment]
Additionally, the log-out button needs to be made. and testing adjusted

**Comment by Vasi012** [comment]
Log in / Log Out / Register / Edit Account / Update Account / Email Verification, rest allauth has been set accordingly. Users can now Create an account, and Log into their account to be able to see the blog section.
